# Generated by Django 4.0.3 on 2023-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
